"""``codegraph instructions`` -- the paragraph that tells an agent to use the graph.

The MCP server already ships instructions of its own, and a client that reads
them needs nothing here. This exists for the other half of the problem: repo
files like ``AGENTS.md`` are read by every agent, they outlive any one session,
and they are where a project says *this* codebase is indexed -- with the two or
three facts that make the case concretely, measured off the graph rather than
guessed.

Nothing here writes unasked. ``init`` sets up files codegraph owns; an agent
file belongs to whoever wrote it, so inserting the block is a separate,
explicit command, and it never creates a file that is not already there.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

from .config import Config

MARKER_START = "<!-- codegraph:start -->"
MARKER_END = "<!-- codegraph:end -->"
GENERATED_NOTE = (
    "<!-- generated by `codegraph instructions`; edits between the markers are overwritten -->"
)

# Agent files, most specific first. Claude Code reads CLAUDE.md and not
# AGENTS.md, so a repo carrying both usually points one at the other.
AGENT_FILES = ("AGENTS.md", "CLAUDE.md")

# Files worth naming in the cost table: big enough that reading one is a real
# decision, and only the worst few, or the table stops being read.
COST_SAMPLE = 3
COST_MIN_BYTES = 12_000
# Tokens per character, near enough for code and honest about being an
# estimate. The point is the ratio, which no rounding here can flatter.
CHARS_PER_TOKEN = 4

_ROWS: tuple[tuple[str, str], ...] = (
    ("bearings in an unfamiliar area", "get_project_overview()"),
    ("every layer touching one entity", 'get_domain_slice("orders")'),
    ("find a symbol by name or docstring", 'search_symbol("...")'),
    ("one declaration, with source if short", 'get_definition("name")'),
    ("what breaks if I change this", 'get_callers("name")'),
    ("what a function does, without reading it", 'get_callees("name")'),
    ("context around an unfamiliar symbol", 'get_neighbors("name")'),
    ("what is in a file", 'get_file_outline("path")'),
    ("which file do I want", 'get_directory_outline("path")'),
    ("module boundaries", 'get_imports("path")'),
    ("what I am editing and what it breaks", "get_change_impact()"),
)
_ENDPOINT_ROW = ("an HTTP route end to end", 'trace_endpoint("/orders/{id}")')


def render(config: Config) -> str:
    """The block, tailored to this project as far as the graph allows."""
    measured, has_endpoints = _measure(config)

    rows = [*_ROWS]
    if has_endpoints:
        rows.append(_ENDPOINT_ROW)

    lines = [
        MARKER_START,
        GENERATED_NOTE,
        "## Query the code graph before reading files",
        "",
        "This repo is indexed by `codegraph` and served over MCP. The graph answers",
        '"where is it declared", "who calls it", "what is in this file" in a few lines;',
        "finding the same answer by reading files costs orders of magnitude more. Reach",
        "for a file only for a body the graph does not carry.",
        "",
        "| What you need | Call |",
        "| --- | --- |",
    ]
    lines += [f"| {need} | `{call}` |" for need, call in rows]

    if measured:
        lines += [
            "",
            "What that saves here, measured on this graph:",
            "",
            "| File | `Read` | `get_file_outline` |",
            "| --- | --- | --- |",
        ]
        lines += [
            f"| `{path}` | {_tokens(read)} | {_tokens(outline)} |"
            for path, read, outline in measured
        ]

    lines += [
        "",
        "A result tagged `[heuristic]` is a name match, not a proven link -- confirm it",
        "before acting on it. `third-party` means the symbol comes from a library and is",
        "not in the graph.",
        "",
        "The graph is a snapshot of the last `codegraph build`. Run it again after",
        "substantial edits: it is incremental and skips unchanged files.",
        MARKER_END,
        "",
    ]
    return "\n".join(lines)


def _measure(config: Config) -> tuple[list[tuple[str, int, int]], bool]:
    """Read-vs-outline cost for the heaviest files, and whether routes exist.

    A missing or unreadable graph is not an error: the block is still worth
    having before the first build, just without the numbers that need one.
    """
    if not config.db_path.exists():
        return [], config.bridge.enabled

    from .server.tools import GraphTools

    try:
        tools = GraphTools(config)
    except (sqlite3.Error, OSError):
        return [], config.bridge.enabled

    try:
        heaviest = tools.db.conn.execute(
            "SELECT path, size_bytes FROM files WHERE size_bytes >= ? "
            "ORDER BY size_bytes DESC LIMIT ?",
            (COST_MIN_BYTES, COST_SAMPLE),
        ).fetchall()
        endpoints = tools.db.conn.execute(
            "SELECT count(*) FROM nodes WHERE type = 'endpoint'"
        ).fetchone()[0]
        measured = []
        for row in heaviest:
            # The real outline, not an estimate of one: whatever truncation
            # `server.max_results` applies is part of what the agent would pay.
            outline = tools.get_file_outline(row["path"])
            measured.append(
                (
                    row["path"],
                    row["size_bytes"] // CHARS_PER_TOKEN,
                    len(outline) // CHARS_PER_TOKEN,
                )
            )
    except sqlite3.Error:
        return [], config.bridge.enabled
    finally:
        tools.close()

    return measured, bool(endpoints) or config.bridge.enabled


def _tokens(count: int) -> str:
    """A token count nobody should read as exact."""
    if count >= 1000:
        return f"~{count / 1000:.1f}k tokens".replace(".0k", "k")
    return f"~{count} tokens"


def default_target(root: Path) -> Path | None:
    """The agent file already in the project, if there is one."""
    for name in AGENT_FILES:
        candidate = root / name
        if candidate.is_file():
            return candidate
    return None


def insert(existing: str, block: str) -> str:
    """Put the block into an agent file: replacing an old one, or appended.

    Markers rather than a whole managed file, because the interesting content
    around the block belongs to a human and a refresh must not disturb it.
    """
    start = existing.find(MARKER_START)
    end = existing.find(MARKER_END)
    if start != -1 and end > start:
        head = existing[:start]
        tail = existing[end + len(MARKER_END) :].lstrip("\n")
        body = block.rstrip("\n") + "\n"
        return head + body + (f"\n{tail}" if tail else "")
    if not existing:
        return block
    head = existing if existing.endswith("\n") else existing + "\n"
    return f"{head}\n{block}"


def has_block(existing: str) -> bool:
    return MARKER_START in existing


def write_block(path: Path, block: str) -> bool:
    """Insert the block into an existing file. True if it replaced an old one."""
    existing = path.read_text(encoding="utf-8")
    refreshed = has_block(existing)
    path.write_text(insert(existing, block), encoding="utf-8", newline="\n")
    return refreshed


def claude_reads(root: Path, target: Path) -> bool:
    """Whether Claude Code will actually load a block written to ``target``.

    It reads CLAUDE.md, never AGENTS.md; the documented bridge is a CLAUDE.md
    that imports the other file with ``@AGENTS.md``.
    """
    if target.name == "CLAUDE.md":
        return True
    claude_md = root / "CLAUDE.md"
    if not claude_md.is_file():
        return False
    try:
        return f"@{target.name}" in claude_md.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
